export const ABOUT = {
  fullName: "CHOUAKÉ DIANA STACY",
  shortBio:
    "Je suis CHOUAKE Diana Stacy prothésiste ongulaire résineuse originaire du Cameroun. Diplômée d'un DTS en esthétique (Diplôme de Technicienne Spécialisé) 2ᵉ national et d'un DQP en coiffure (Diplôme de Qualification Professionnel) 2ᵉ national. Je n'ai pas toujours baigné dans l'univers de la beauté ; par le passé j'étais convaincu que j'avais une carrière brillante en tant qu'infirmière… mais au bout de deux ans je me suis rendue compte qu'il fallait que je vive de ma passion. Depuis toute petite j'ai toujours été douée en dessin, ce qui m'avait valu un prix lors d'un concours de dessin au primaire. Je suis de ceux qui pensent que le bonheur réside autour des détails. Le déclic m'est parvenu ce jour où j'ai vécu mon premier cours d'onglerie donné par un homme utilisant ma couleur préférée pour expliquer l'application du vernis, et des années plus tard cette étincelle brûle toujours dans mon regard.",
  bioIntro: "Mes Salutations",
  bioFull: [
    { text: "Je suis CHOUAKE Diana Stacy ", bold: false },
    { text: "prothésiste ongulaire résineuse", bold: true },
    { text: " originaire du Cameroun. Diplômée d'un DTS en esthétique (Diplôme de Technicienne Spécialisé) 2ᵉ national et d'un DQP en coiffure (Diplôme de Qualification Professionnel) 2ᵉ national. Je n'ai pas toujours baigné dans l'univers de la beauté ; par le passé j'étais convaincue que j'avais une carrière brillante en tant qu'infirmière… mais au bout de deux ans je me suis rendue compte qu'il fallait que je vive de ma ", bold: false },
    { text: "passion", bold: true },
    { text: ". Depuis toute petite j'ai toujours été douée en dessin, ce qui m'avait valu un prix lors d'un concours de dessin au primaire. Je suis de ceux qui pensent que le bonheur réside autour des détails. Le déclic m'est parvenu ce jour où j'ai vécu mon premier cours d'onglerie donné par un homme utilisant ma couleur préférée pour expliquer l'application du vernis, et des années plus tard cette étincelle brûle toujours dans mon regard.", bold: false },
    { text: " J'ai rarement eu le sentiment d'appartenir à un univers différent de celui-ci, un univers dans lequel chaque jour est une agréable découverte de ma personnalité et ma passion pour l'art. Je ne fais pas que ", bold: false },
    { text: "\"poser des ongles\"", bold: true },
    { text: ", c'est un long processus d'apprentissage que je me discipline à suivre avec sourire. Je façonne mon bonheur à redonner le sourire et la ", bold: false },
    { text: "confiance en soi", bold: true },
    { text: " à des femmes qui le méritent. Je tire mon inspiration des autres prothésistes, de la mode, de la nature et aussi de la musique. Je me suis forgée une place dans le monde de l'entrepreneuriat et j'aimerais élargir mes horizons et me plonger dans l'industrie de l'onglerie pour exprimer mon ", bold: false },
    { text: "talent", bold: true },
    { text: " et grandir dans le monde professionnel.", bold: false },
  ],
  parcours: [
    { year: "2016 - 2017", event: "Baccalauréat D — Lycée De Makepé" },
    { year: "2021 / 2022", event: "CFPE DE DOUALA" },
    { year: "", event: "DTS en esthétique (Diplôme de Technicienne Spécialisé) 2ᵉ national" },
    { year: "", event: "DQP en coiffure (Diplôme de Qualification Professionnel) 2ᵉ national" },
  ],
  vision:
    "Créer et innover constamment dans l'industrie de la beauté et être à l'avant-garde de la mode, en créant toujours des tendances dans le 'Nail Art'.",
  mission: [
    "Donner plus de légitimité à la profession de prothésiste ongulaire.",
    "Me prouver que je peux être une femme inspirante.",
    "Satisfaire aux attentes des clients.",
    "Aider les femmes à avoir plus confiance en elles grâce à mon travail.",
  ],
  competences: [
    "Nail artist",
    "Manucure / Pédicure",
    "Soin de pieds / Mains",
    "Make up",
    "Soins Esthétiques Mixtes",
    "Coiffure Femme",
    "Épilation à la cire",
    "Fabrication de Press On Nails",
  ],
  langues: ["Français", "Anglais"],
  photo: "/gallery/stacy-portrait-04-roses.webp",
} as const;

export const EXPERIENCE = [
  {
    year: "2023",
    company: "Esfon Hair",
    role: "Prothésiste Ongulaire Résineuse",
    description:
      "Découvrir et me familiariser au milieu professionnel. Participer à l'évolution de l'industrie des ongles.",
  },
] as const;

export const SERVICES = [
  {
    title: "Pose Complète",
    description:
      "Extensions gel, acryl ou capsules sur mesure. Pose complète avec décoloration, mise en forme et finition parfaite.",
    features: ["Gel", "Acryl", "Capsules", "Refill"],
    icon: "nails",
  },
  {
    title: "Nail Art & Décoration",
    description:
      "Designs créatifs, pierres, strass, motifs sur mesure. Chaque set est une œuvre d'art unique qui vous ressemble.",
    features: ["Strass & Pierres", "Motifs Peints", "Effets Speciaux", "Tendances"],
    icon: "sparkles",
  },
] as const;

export interface ProjectPhoto {
  src: string;
  alt: string;
  label: string;
}

export interface Project {
  name: string;
  description: string;
  photos: ProjectPhoto[];
}

export const PROJECTS: Project[] = [
  {
    name: "Projet 1 — Du naturel à l'artistique",
    description: "Transformation complète : de l'ongle naturel à la pose artistique finalisée.",
    photos: [
      { src: "/gallery/projet1-01-initial.jpeg", alt: "Ongles naturels avant la pose", label: "Avant" },
      { src: "/gallery/projet1-02.jpeg", alt: "Étape de construction", label: "Étape 1" },
      { src: "/gallery/projet1-03.jpeg", alt: "Étape de modelage", label: "Étape 2" },
      { src: "/gallery/projet1-04.jpeg", alt: "Étape de préparation", label: "Étape 3" },
      { src: "/gallery/projet1-05-rendu.jpeg", alt: "Rendu presque final", label: "Rendu" },
      { src: "/gallery/projet1-06-final.jpeg", alt: "Pose complète finalisée", label: "Final" },
    ],
  },
  {
    name: "Projet 2 — Pose longue élégante",
    description: "Extensions longues avec finition soignée et design raffiné.",
    photos: [
      { src: "/gallery/projet2-01.jpeg", alt: "Début de pose", label: "Début" },
      { src: "/gallery/projet2-02.jpeg", alt: "Construction en cours", label: "Étape 1" },
      { src: "/gallery/projet2-03.jpeg", alt: "Affinage du shape", label: "Étape 2" },
      { src: "/gallery/projet2-04.jpeg", alt: "Rendu final", label: "Final" },
    ],
  },
  {
    name: "Projet 3",
    description: "Ensemble de créations ongulaires.",
    photos: [
      { src: "/gallery/projet3-01.jpeg", alt: "Création 1", label: "Vue 1" },
      { src: "/gallery/projet3-02.jpeg", alt: "Création 2", label: "Vue 2" },
    ],
  },
  {
    name: "Projet 4 — Pose artistique",
    description: "Création artistique avec design sur mesure et finition impeccable.",
    photos: [
      { src: "/gallery/projet04-01.jpeg", alt: "Début de pose", label: "Début" },
      { src: "/gallery/projet04-02.jpeg", alt: "Construction en cours", label: "Étape 1" },
      { src: "/gallery/projet04-03.jpeg", alt: "Rendu final", label: "Final" },
    ],
  },
  {
    name: "Projet 5 — Set complet",
    description: "Pose complète avec nail art détaillé et finition professionnelle.",
    photos: [
      { src: "/gallery/projet5-01.jpeg", alt: "Préparation", label: "Début" },
      { src: "/gallery/projet5-02.jpeg", alt: "Construction", label: "Étape 1" },
      { src: "/gallery/projet5-03.jpeg", alt: "Décoration", label: "Étape 2" },
      { src: "/gallery/projet5-04.jpeg", alt: "Affinage", label: "Étape 3" },
      { src: "/gallery/projet5-05.jpeg", alt: "Détails finaux", label: "Étape 4" },
      { src: "/gallery/projet5-06.jpeg", alt: "Rendu final", label: "Final" },
    ],
  },
];

export interface GalleryPhoto {
  src: string;
  alt: string;
  description: string;
  category: "Gel" | "Acryl" | "Nail Art";
}

export const GALLERY_PHOTOS: GalleryPhoto[] = [
  { src: "/gallery/creation-ongulaire-01.webp", alt: "Création ongulaire animal print", description: "Construction résine nude taille L forme carré + tigé orange + zèbre + strass", category: "Nail Art" },
  { src: "/gallery/creation-ongulaire-02.webp", alt: "Nail art animal print angle différent", description: "Construction résine nude taille L forme carré + tigé orange + zèbre + strass", category: "Nail Art" },
  { src: "/gallery/creation-ongulaire-03.webp", alt: "Nail art violet à pois", description: "Vernis gel violet avec pois blancs et studs dorés", category: "Gel" },
  { src: "/gallery/creation-ongulaire-04.webp", alt: "Création florale tropicale", description: "Construction résine nude taille L forme carré + zèbre + fleurs 3D orange", category: "Nail Art" },
  { src: "/gallery/creation-ongulaire-05.webp", alt: "Nail art floral angle différent", description: "Construction résine nude taille L forme carré + zèbre + fleurs 3D orange", category: "Nail Art" },
  { src: "/gallery/creation-ongulaire-06.webp", alt: "French bleu nuage", description: "Construction résine nude taille M forme carré + French bleu nuage + charme doré", category: "Acryl" },
  { src: "/gallery/creation-ongulaire-07.webp", alt: "Création artistique bourgogne", description: "Construction résine amande taille L + bourgogne + feuilles dorées + fleurs", category: "Nail Art" },
  { src: "/gallery/creation-ongulaire-08.webp", alt: "Nail art artistic detail", description: "Construction résine amande taille L + bourgogne + feuilles dorées + fleurs", category: "Nail Art" },
  { src: "/gallery/creation-ongulaire-09.webp", alt: "French élégante bourgogne", description: "Construction résine stiletto taille L + bourgogne + blanc + croco + studs", category: "Acryl" },
  { src: "/gallery/creation-ongulaire-10.webp", alt: "French élégante deux mains", description: "Construction résine stiletto taille L + bourgogne + blanc + croco + studs", category: "Acryl" },
  { src: "/gallery/creation-ongulaire-11.webp", alt: "Cat eye magnétique vert", description: "Construction résine amande taille M + nude + vert chat magnétique", category: "Gel" },
  { src: "/gallery/creation-ongulaire-12.webp", alt: "Cat eye magnétique detail", description: "Construction résine amande taille M + nude + vert chat magnétique", category: "Gel" },
  { src: "/gallery/creation-ongulaire-13.webp", alt: "Flammes vibrant", description: "Construction résine stiletto taille XL + flammes rose/orange/jaune sur nude", category: "Nail Art" },
  { src: "/gallery/creation-ongulaire-14.webp", alt: "Nail art rose avec nœud 3D", description: "Construction résine taille M forme carré + rose/blanc + nœud papillon 3D + cœur", category: "Nail Art" },
  { src: "/gallery/creation-ongulaire-15.webp", alt: "French lilas feuilles", description: "Construction résine taille L forme carré + French lilas + feuilles noires + paillettes", category: "Acryl" },
  { src: "/gallery/creation-ongulaire-16-popart.webp", alt: "Nail art pop art coloré", description: "Construction résine taille XL forme carré + nail art pop art coloré (fleurs, visages)", category: "Nail Art" },
  { src: "/gallery/vague03-2077.jpeg", alt: "Création ongulaire", description: "Pose ongulaire avec finition professionnelle", category: "Nail Art" },
  { src: "/gallery/vague03-3046.jpeg", alt: "Création ongulaire", description: "Construction et modelage d'ongles", category: "Gel" },
  { src: "/gallery/vague03-3047.jpeg", alt: "Création ongulaire détail", description: "Détail de pose ongulaire", category: "Gel" },
  { src: "/gallery/projet04-03.jpeg", alt: "Projet 4 rendu final", description: "Création artistique avec design sur mesure", category: "Nail Art" },
  { src: "/gallery/projet5-06.jpeg", alt: "Projet 5 rendu final", description: "Set complet avec nail art détaillé", category: "Nail Art" },
  { src: "/gallery/instagram/ig-001.jpg", alt: "Création Instagram 1", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-002.jpg", alt: "Création Instagram 2", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-003.jpg", alt: "Création Instagram 3", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-004.jpg", alt: "Création Instagram 4", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-005.jpg", alt: "Création Instagram 5", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-006.jpg", alt: "Création Instagram 6", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-007.jpg", alt: "Création Instagram 7", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-008.jpg", alt: "Création Instagram 8", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-009.jpg", alt: "Création Instagram 9", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-010.jpg", alt: "Création Instagram 10", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-011.jpg", alt: "Création Instagram 11", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-012.jpg", alt: "Création Instagram 12", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-013.jpg", alt: "Création Instagram 13", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-014.jpg", alt: "Création Instagram 14", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-015.jpg", alt: "Création Instagram 15", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-016.jpg", alt: "Création Instagram 16", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-017.jpg", alt: "Création Instagram 17", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-018.jpg", alt: "Création Instagram 18", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-019.jpg", alt: "Création Instagram 19", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-020.jpg", alt: "Création Instagram 20", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-021.jpg", alt: "Création Instagram 21", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-022.jpg", alt: "Création Instagram 22", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-023.jpg", alt: "Création Instagram 23", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-024.jpg", alt: "Création Instagram 24", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-025.jpg", alt: "Création Instagram 25", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-026.jpg", alt: "Création Instagram 26", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-027.jpg", alt: "Création Instagram 27", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-028.jpg", alt: "Création Instagram 28", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-029.jpg", alt: "Création Instagram 29", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-030.jpg", alt: "Création Instagram 30", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-031.jpg", alt: "Création Instagram 31", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-032.jpg", alt: "Création Instagram 32", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-033.jpg", alt: "Création Instagram 33", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-034.jpg", alt: "Création Instagram 34", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-035.jpg", alt: "Création Instagram 35", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-036.jpg", alt: "Création Instagram 36", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-037.jpg", alt: "Création Instagram 37", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-038.jpg", alt: "Création Instagram 38", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-039.jpg", alt: "Création Instagram 39", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-040.jpg", alt: "Création Instagram 40", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-041.jpg", alt: "Création Instagram 41", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-042.jpg", alt: "Création Instagram 42", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-043.jpg", alt: "Création Instagram 43", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-044.jpg", alt: "Création Instagram 44", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-045.jpg", alt: "Création Instagram 45", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-046.jpg", alt: "Création Instagram 46", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-047.jpg", alt: "Création Instagram 47", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-048.jpg", alt: "Création Instagram 48", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-049.jpg", alt: "Création Instagram 49", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-050.jpg", alt: "Création Instagram 50", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-051.jpg", alt: "Création Instagram 51", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-052.jpg", alt: "Création Instagram 52", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-053.jpg", alt: "Création Instagram 53", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-054.jpg", alt: "Création Instagram 54", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-055.jpg", alt: "Création Instagram 55", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-056.jpg", alt: "Création Instagram 56", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-057.jpg", alt: "Création Instagram 57", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-058.jpg", alt: "Création Instagram 58", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-059.jpg", alt: "Création Instagram 59", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-060.jpg", alt: "Création Instagram 60", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-061.jpg", alt: "Création Instagram 61", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-062.jpg", alt: "Création Instagram 62", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-063.jpg", alt: "Création Instagram 63", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-064.jpg", alt: "Création Instagram 64", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-065.jpg", alt: "Création Instagram 65", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-066.jpg", alt: "Création Instagram 66", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-067.jpg", alt: "Création Instagram 67", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-068.jpg", alt: "Création Instagram 68", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-069.jpg", alt: "Création Instagram 69", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-070.jpg", alt: "Création Instagram 70", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-071.jpg", alt: "Création Instagram 71", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-072.jpg", alt: "Création Instagram 72", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-073.jpg", alt: "Création Instagram 73", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-074.jpg", alt: "Création Instagram 74", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-075.jpg", alt: "Création Instagram 75", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-076.jpg", alt: "Création Instagram 76", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-077.jpg", alt: "Création Instagram 77", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-078.jpg", alt: "Création Instagram 78", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-079.jpg", alt: "Création Instagram 79", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-080.jpg", alt: "Création Instagram 80", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-081.jpg", alt: "Création Instagram 81", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-082.jpg", alt: "Création Instagram 82", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-083.jpg", alt: "Création Instagram 83", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-084.jpg", alt: "Création Instagram 84", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-085.jpg", alt: "Création Instagram 85", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-086.jpg", alt: "Création Instagram 86", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-087.jpg", alt: "Création Instagram 87", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-088.jpg", alt: "Création Instagram 88", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-089.jpg", alt: "Création Instagram 89", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-090.jpg", alt: "Création Instagram 90", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-091.jpg", alt: "Création Instagram 91", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-092.jpg", alt: "Création Instagram 92", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-093.jpg", alt: "Création Instagram 93", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-094.jpg", alt: "Création Instagram 94", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-095.jpg", alt: "Création Instagram 95", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-096.jpg", alt: "Création Instagram 96", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-097.jpg", alt: "Création Instagram 97", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-098.jpg", alt: "Création Instagram 98", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-099.jpg", alt: "Création Instagram 99", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-100.jpg", alt: "Création Instagram 100", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-101.jpg", alt: "Création Instagram 101", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-102.jpg", alt: "Création Instagram 102", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-103.jpg", alt: "Création Instagram 103", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-104.jpg", alt: "Création Instagram 104", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-105.jpg", alt: "Création Instagram 105", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-106.jpg", alt: "Création Instagram 106", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-107.jpg", alt: "Création Instagram 107", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-108.jpg", alt: "Création Instagram 108", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-109.jpg", alt: "Création Instagram 109", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-110.jpg", alt: "Création Instagram 110", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-111.jpg", alt: "Création Instagram 111", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-112.jpg", alt: "Création Instagram 112", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-113.jpg", alt: "Création Instagram 113", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-114.jpg", alt: "Création Instagram 114", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-115.jpg", alt: "Création Instagram 115", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-116.jpg", alt: "Création Instagram 116", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-117.jpg", alt: "Création Instagram 117", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-118.jpg", alt: "Création Instagram 118", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-119.jpg", alt: "Création Instagram 119", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-120.jpg", alt: "Création Instagram 120", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-121.jpg", alt: "Création Instagram 121", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram/ig-122.jpg", alt: "Création Instagram 122", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-123.jpg", alt: "Création Instagram 123", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-124.jpg", alt: "Création Instagram 124", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-125.jpg", alt: "Création Instagram 125", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-126.jpg", alt: "Création Instagram 126", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-127.jpg", alt: "Création Instagram 127", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-128.jpg", alt: "Création Instagram 128", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-129.jpg", alt: "Création Instagram 129", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-130.jpg", alt: "Création Instagram 130", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-131.jpg", alt: "Création Instagram 131", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-132.jpg", alt: "Création Instagram 132", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-133.jpg", alt: "Création Instagram 133", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-134.jpg", alt: "Création Instagram 134", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-135.jpg", alt: "Création Instagram 135", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-136.jpg", alt: "Création Instagram 136", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-137.jpg", alt: "Création Instagram 137", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-138.jpg", alt: "Création Instagram 138", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-139.jpg", alt: "Création Instagram 139", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-140.jpg", alt: "Création Instagram 140", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-141.jpg", alt: "Création Instagram 141", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-142.jpg", alt: "Création Instagram 142", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-143.jpg", alt: "Création Instagram 143", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-144.jpg", alt: "Création Instagram 144", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-145.jpg", alt: "Création Instagram 145", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-146.jpg", alt: "Création Instagram 146", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-147.jpg", alt: "Création Instagram 147", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-148.jpg", alt: "Création Instagram 148", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-149.jpg", alt: "Création Instagram 149", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-150.jpg", alt: "Création Instagram 150", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-151.jpg", alt: "Création Instagram 151", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-152.jpg", alt: "Création Instagram 152", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-153.jpg", alt: "Création Instagram 153", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-154.jpg", alt: "Création Instagram 154", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-155.jpg", alt: "Création Instagram 155", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-156.jpg", alt: "Création Instagram 156", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-157.jpg", alt: "Création Instagram 157", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-158.jpg", alt: "Création Instagram 158", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-159.jpg", alt: "Création Instagram 159", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-160.jpg", alt: "Création Instagram 160", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-161.jpg", alt: "Création Instagram 161", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-162.jpg", alt: "Création Instagram 162", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-163.jpg", alt: "Création Instagram 163", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-164.jpg", alt: "Création Instagram 164", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-165.jpg", alt: "Création Instagram 165", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-166.jpg", alt: "Création Instagram 166", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-167.jpg", alt: "Création Instagram 167", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-168.jpg", alt: "Création Instagram 168", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-169.jpg", alt: "Création Instagram 169", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-170.jpg", alt: "Création Instagram 170", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-171.jpg", alt: "Création Instagram 171", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-172.jpg", alt: "Création Instagram 172", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-173.jpg", alt: "Création Instagram 173", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-174.jpg", alt: "Création Instagram 174", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-175.jpg", alt: "Création Instagram 175", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-176.jpg", alt: "Création Instagram 176", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-177.jpg", alt: "Création Instagram 177", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-178.jpg", alt: "Création Instagram 178", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-179.jpg", alt: "Création Instagram 179", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-180.jpg", alt: "Création Instagram 180", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-181.jpg", alt: "Création Instagram 181", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-182.jpg", alt: "Création Instagram 182", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-183.jpg", alt: "Création Instagram 183", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-184.jpg", alt: "Création Instagram 184", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-185.jpg", alt: "Création Instagram 185", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-186.jpg", alt: "Création Instagram 186", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-187.jpg", alt: "Création Instagram 187", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-188.jpg", alt: "Création Instagram 188", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-189.jpg", alt: "Création Instagram 189", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-190.jpg", alt: "Création Instagram 190", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-191.jpg", alt: "Création Instagram 191", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-192.jpg", alt: "Création Instagram 192", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-193.jpg", alt: "Création Instagram 193", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-194.jpg", alt: "Création Instagram 194", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-195.jpg", alt: "Création Instagram 195", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-196.jpg", alt: "Création Instagram 196", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-197.jpg", alt: "Création Instagram 197", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-198.jpg", alt: "Création Instagram 198", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-199.jpg", alt: "Création Instagram 199", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-200.jpg", alt: "Création Instagram 200", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-201.jpg", alt: "Création Instagram 201", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-202.jpg", alt: "Création Instagram 202", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-203.jpg", alt: "Création Instagram 203", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-204.jpg", alt: "Création Instagram 204", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-205.jpg", alt: "Création Instagram 205", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-206.jpg", alt: "Création Instagram 206", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-207.jpg", alt: "Création Instagram 207", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-208.jpg", alt: "Création Instagram 208", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-209.jpg", alt: "Création Instagram 209", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-210.jpg", alt: "Création Instagram 210", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-211.jpg", alt: "Création Instagram 211", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-212.jpg", alt: "Création Instagram 212", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-213.jpg", alt: "Création Instagram 213", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-214.jpg", alt: "Création Instagram 214", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-215.jpg", alt: "Création Instagram 215", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-216.jpg", alt: "Création Instagram 216", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-217.jpg", alt: "Création Instagram 217", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-218.jpg", alt: "Création Instagram 218", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-219.jpg", alt: "Création Instagram 219", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-220.jpg", alt: "Création Instagram 220", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-221.jpg", alt: "Création Instagram 221", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-222.jpg", alt: "Création Instagram 222", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-223.jpg", alt: "Création Instagram 223", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-224.jpg", alt: "Création Instagram 224", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-225.jpg", alt: "Création Instagram 225", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-226.jpg", alt: "Création Instagram 226", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-227.jpg", alt: "Création Instagram 227", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-228.jpg", alt: "Création Instagram 228", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-229.jpg", alt: "Création Instagram 229", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-230.jpg", alt: "Création Instagram 230", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-231.jpg", alt: "Création Instagram 231", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-232.jpg", alt: "Création Instagram 232", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-233.jpg", alt: "Création Instagram 233", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-234.jpg", alt: "Création Instagram 234", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-235.jpg", alt: "Création Instagram 235", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-236.jpg", alt: "Création Instagram 236", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-237.jpg", alt: "Création Instagram 237", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-238.jpg", alt: "Création Instagram 238", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-239.jpg", alt: "Création Instagram 239", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-240.jpg", alt: "Création Instagram 240", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-241.jpg", alt: "Création Instagram 241", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-242.jpg", alt: "Création Instagram 242", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-243.jpg", alt: "Création Instagram 243", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-244.jpg", alt: "Création Instagram 244", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-245.jpg", alt: "Création Instagram 245", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-246.jpg", alt: "Création Instagram 246", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-247.jpg", alt: "Création Instagram 247", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-248.jpg", alt: "Création Instagram 248", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-249.jpg", alt: "Création Instagram 249", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-250.jpg", alt: "Création Instagram 250", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-251.jpg", alt: "Création Instagram 251", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-252.jpg", alt: "Création Instagram 252", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-253.jpg", alt: "Création Instagram 253", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-254.jpg", alt: "Création Instagram 254", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-255.jpg", alt: "Création Instagram 255", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-256.jpg", alt: "Création Instagram 256", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-257.jpg", alt: "Création Instagram 257", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-258.jpg", alt: "Création Instagram 258", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-259.jpg", alt: "Création Instagram 259", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-260.jpg", alt: "Création Instagram 260", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-261.jpg", alt: "Création Instagram 261", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-262.jpg", alt: "Création Instagram 262", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-263.jpg", alt: "Création Instagram 263", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-264.jpg", alt: "Création Instagram 264", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-265.jpg", alt: "Création Instagram 265", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-266.jpg", alt: "Création Instagram 266", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-267.jpg", alt: "Création Instagram 267", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-268.jpg", alt: "Création Instagram 268", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-269.jpg", alt: "Création Instagram 269", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-270.jpg", alt: "Création Instagram 270", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-271.jpg", alt: "Création Instagram 271", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-272.jpg", alt: "Création Instagram 272", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-273.jpg", alt: "Création Instagram 273", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-274.jpg", alt: "Création Instagram 274", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-275.jpg", alt: "Création Instagram 275", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-276.jpg", alt: "Création Instagram 276", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-277.jpg", alt: "Création Instagram 277", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-278.jpg", alt: "Création Instagram 278", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-279.jpg", alt: "Création Instagram 279", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-280.jpg", alt: "Création Instagram 280", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-281.jpg", alt: "Création Instagram 281", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-282.jpg", alt: "Création Instagram 282", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-283.jpg", alt: "Création Instagram 283", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-284.jpg", alt: "Création Instagram 284", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-285.jpg", alt: "Création Instagram 285", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-286.jpg", alt: "Création Instagram 286", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-287.jpg", alt: "Création Instagram 287", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-288.jpg", alt: "Création Instagram 288", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-289.jpg", alt: "Création Instagram 289", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-290.jpg", alt: "Création Instagram 290", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-291.jpg", alt: "Création Instagram 291", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-292.jpg", alt: "Création Instagram 292", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-293.jpg", alt: "Création Instagram 293", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-294.jpg", alt: "Création Instagram 294", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-295.jpg", alt: "Création Instagram 295", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-296.jpg", alt: "Création Instagram 296", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-297.jpg", alt: "Création Instagram 297", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-298.jpg", alt: "Création Instagram 298", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-299.jpg", alt: "Création Instagram 299", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-300.jpg", alt: "Création Instagram 300", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-301.jpg", alt: "Création Instagram 301", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-302.jpg", alt: "Création Instagram 302", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-303.jpg", alt: "Création Instagram 303", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-304.jpg", alt: "Création Instagram 304", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-305.jpg", alt: "Création Instagram 305", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-306.jpg", alt: "Création Instagram 306", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-307.jpg", alt: "Création Instagram 307", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-308.jpg", alt: "Création Instagram 308", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-309.jpg", alt: "Création Instagram 309", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-310.jpg", alt: "Création Instagram 310", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-311.jpg", alt: "Création Instagram 311", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-312.jpg", alt: "Création Instagram 312", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-313.jpg", alt: "Création Instagram 313", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-314.jpg", alt: "Création Instagram 314", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-315.jpg", alt: "Création Instagram 315", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-316.jpg", alt: "Création Instagram 316", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-317.jpg", alt: "Création Instagram 317", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-318.jpg", alt: "Création Instagram 318", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-319.jpg", alt: "Création Instagram 319", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-320.jpg", alt: "Création Instagram 320", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-321.jpg", alt: "Création Instagram 321", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-322.jpg", alt: "Création Instagram 322", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-323.jpg", alt: "Création Instagram 323", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-324.jpg", alt: "Création Instagram 324", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-325.jpg", alt: "Création Instagram 325", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-326.jpg", alt: "Création Instagram 326", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-327.jpg", alt: "Création Instagram 327", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-328.jpg", alt: "Création Instagram 328", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-329.jpg", alt: "Création Instagram 329", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-330.jpg", alt: "Création Instagram 330", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-331.jpg", alt: "Création Instagram 331", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-332.jpg", alt: "Création Instagram 332", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-333.jpg", alt: "Création Instagram 333", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-334.jpg", alt: "Création Instagram 334", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-335.jpg", alt: "Création Instagram 335", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-336.jpg", alt: "Création Instagram 336", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-337.jpg", alt: "Création Instagram 337", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-338.jpg", alt: "Création Instagram 338", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-339.jpg", alt: "Création Instagram 339", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-340.jpg", alt: "Création Instagram 340", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-341.jpg", alt: "Création Instagram 341", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-342.jpg", alt: "Création Instagram 342", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-343.jpg", alt: "Création Instagram 343", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-344.jpg", alt: "Création Instagram 344", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-345.jpg", alt: "Création Instagram 345", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-346.jpg", alt: "Création Instagram 346", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-347.jpg", alt: "Création Instagram 347", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-348.jpg", alt: "Création Instagram 348", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-349.jpg", alt: "Création Instagram 349", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-350.jpg", alt: "Création Instagram 350", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-351.jpg", alt: "Création Instagram 351", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-352.jpg", alt: "Création Instagram 352", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-353.jpg", alt: "Création Instagram 353", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-354.jpg", alt: "Création Instagram 354", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-355.jpg", alt: "Création Instagram 355", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-356.jpg", alt: "Création Instagram 356", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-357.jpg", alt: "Création Instagram 357", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-358.jpg", alt: "Création Instagram 358", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-359.jpg", alt: "Création Instagram 359", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-360.jpg", alt: "Création Instagram 360", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-361.jpg", alt: "Création Instagram 361", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-362.jpg", alt: "Création Instagram 362", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-363.jpg", alt: "Création Instagram 363", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-364.jpg", alt: "Création Instagram 364", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-365.jpg", alt: "Création Instagram 365", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-366.jpg", alt: "Création Instagram 366", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-367.jpg", alt: "Création Instagram 367", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-368.jpg", alt: "Création Instagram 368", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-369.jpg", alt: "Création Instagram 369", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-370.jpg", alt: "Création Instagram 370", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-371.jpg", alt: "Création Instagram 371", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-372.jpg", alt: "Création Instagram 372", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-373.jpg", alt: "Création Instagram 373", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-374.jpg", alt: "Création Instagram 374", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-375.jpg", alt: "Création Instagram 375", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-376.jpg", alt: "Création Instagram 376", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-377.jpg", alt: "Création Instagram 377", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-378.jpg", alt: "Création Instagram 378", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-379.jpg", alt: "Création Instagram 379", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-380.jpg", alt: "Création Instagram 380", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-381.jpg", alt: "Création Instagram 381", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-382.jpg", alt: "Création Instagram 382", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-383.jpg", alt: "Création Instagram 383", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-384.jpg", alt: "Création Instagram 384", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-385.jpg", alt: "Création Instagram 385", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-386.jpg", alt: "Création Instagram 386", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-387.jpg", alt: "Création Instagram 387", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-388.jpg", alt: "Création Instagram 388", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-389.jpg", alt: "Création Instagram 389", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-390.jpg", alt: "Création Instagram 390", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-391.jpg", alt: "Création Instagram 391", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-392.jpg", alt: "Création Instagram 392", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-393.jpg", alt: "Création Instagram 393", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-394.jpg", alt: "Création Instagram 394", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-395.jpg", alt: "Création Instagram 395", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-396.jpg", alt: "Création Instagram 396", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-397.jpg", alt: "Création Instagram 397", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-398.jpg", alt: "Création Instagram 398", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-399.jpg", alt: "Création Instagram 399", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-400.jpg", alt: "Création Instagram 400", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-401.jpg", alt: "Création Instagram 401", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-402.jpg", alt: "Création Instagram 402", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-403.jpg", alt: "Création Instagram 403", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-404.jpg", alt: "Création Instagram 404", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-405.jpg", alt: "Création Instagram 405", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-406.jpg", alt: "Création Instagram 406", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-407.jpg", alt: "Création Instagram 407", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-408.jpg", alt: "Création Instagram 408", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-409.jpg", alt: "Création Instagram 409", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-410.jpg", alt: "Création Instagram 410", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-411.jpg", alt: "Création Instagram 411", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-412.jpg", alt: "Création Instagram 412", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-413.jpg", alt: "Création Instagram 413", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-414.jpg", alt: "Création Instagram 414", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-415.jpg", alt: "Création Instagram 415", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-416.jpg", alt: "Création Instagram 416", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-417.jpg", alt: "Création Instagram 417", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-418.jpg", alt: "Création Instagram 418", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-419.jpg", alt: "Création Instagram 419", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-420.jpg", alt: "Création Instagram 420", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-421.jpg", alt: "Création Instagram 421", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-422.jpg", alt: "Création Instagram 422", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-423.jpg", alt: "Création Instagram 423", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-424.jpg", alt: "Création Instagram 424", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-425.jpg", alt: "Création Instagram 425", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-426.jpg", alt: "Création Instagram 426", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-427.jpg", alt: "Création Instagram 427", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-428.jpg", alt: "Création Instagram 428", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-429.jpg", alt: "Création Instagram 429", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-430.jpg", alt: "Création Instagram 430", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-431.jpg", alt: "Création Instagram 431", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-432.jpg", alt: "Création Instagram 432", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-433.jpg", alt: "Création Instagram 433", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-434.jpg", alt: "Création Instagram 434", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-435.jpg", alt: "Création Instagram 435", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-436.jpg", alt: "Création Instagram 436", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-437.jpg", alt: "Création Instagram 437", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-438.jpg", alt: "Création Instagram 438", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-439.jpg", alt: "Création Instagram 439", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-440.jpg", alt: "Création Instagram 440", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-441.jpg", alt: "Création Instagram 441", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-442.jpg", alt: "Création Instagram 442", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-443.jpg", alt: "Création Instagram 443", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-444.jpg", alt: "Création Instagram 444", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-445.jpg", alt: "Création Instagram 445", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-446.jpg", alt: "Création Instagram 446", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-447.jpg", alt: "Création Instagram 447", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-448.jpg", alt: "Création Instagram 448", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-449.jpg", alt: "Création Instagram 449", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-450.jpg", alt: "Création Instagram 450", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-451.jpg", alt: "Création Instagram 451", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-452.jpg", alt: "Création Instagram 452", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-453.jpg", alt: "Création Instagram 453", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-454.jpg", alt: "Création Instagram 454", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-455.jpg", alt: "Création Instagram 455", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-456.jpg", alt: "Création Instagram 456", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-457.jpg", alt: "Création Instagram 457", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-458.jpg", alt: "Création Instagram 458", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-459.jpg", alt: "Création Instagram 459", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-460.jpg", alt: "Création Instagram 460", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-461.jpg", alt: "Création Instagram 461", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-462.jpg", alt: "Création Instagram 462", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-463.jpg", alt: "Création Instagram 463", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-464.jpg", alt: "Création Instagram 464", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-465.jpg", alt: "Création Instagram 465", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-466.jpg", alt: "Création Instagram 466", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-467.jpg", alt: "Création Instagram 467", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-468.jpg", alt: "Création Instagram 468", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-469.jpg", alt: "Création Instagram 469", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-470.jpg", alt: "Création Instagram 470", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-471.jpg", alt: "Création Instagram 471", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-472.jpg", alt: "Création Instagram 472", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-473.jpg", alt: "Création Instagram 473", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-474.jpg", alt: "Création Instagram 474", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-475.jpg", alt: "Création Instagram 475", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-476.jpg", alt: "Création Instagram 476", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-477.jpg", alt: "Création Instagram 477", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-478.jpg", alt: "Création Instagram 478", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-479.jpg", alt: "Création Instagram 479", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-480.jpg", alt: "Création Instagram 480", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-481.jpg", alt: "Création Instagram 481", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-482.jpg", alt: "Création Instagram 482", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-483.jpg", alt: "Création Instagram 483", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-484.jpg", alt: "Création Instagram 484", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-485.jpg", alt: "Création Instagram 485", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-486.jpg", alt: "Création Instagram 486", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-487.jpg", alt: "Création Instagram 487", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-488.jpg", alt: "Création Instagram 488", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-489.jpg", alt: "Création Instagram 489", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-490.jpg", alt: "Création Instagram 490", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-491.jpg", alt: "Création Instagram 491", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-492.jpg", alt: "Création Instagram 492", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-493.jpg", alt: "Création Instagram 493", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-494.jpg", alt: "Création Instagram 494", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-495.jpg", alt: "Création Instagram 495", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-496.jpg", alt: "Création Instagram 496", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-497.jpg", alt: "Création Instagram 497", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-498.jpg", alt: "Création Instagram 498", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-499.jpg", alt: "Création Instagram 499", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-500.jpg", alt: "Création Instagram 500", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-501.jpg", alt: "Création Instagram 501", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-502.jpg", alt: "Création Instagram 502", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-503.jpg", alt: "Création Instagram 503", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-504.jpg", alt: "Création Instagram 504", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-505.jpg", alt: "Création Instagram 505", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-506.jpg", alt: "Création Instagram 506", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-507.jpg", alt: "Création Instagram 507", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-508.jpg", alt: "Création Instagram 508", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-509.jpg", alt: "Création Instagram 509", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-510.jpg", alt: "Création Instagram 510", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-511.jpg", alt: "Création Instagram 511", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-512.jpg", alt: "Création Instagram 512", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-513.jpg", alt: "Création Instagram 513", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-514.jpg", alt: "Création Instagram 514", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-515.jpg", alt: "Création Instagram 515", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-516.jpg", alt: "Création Instagram 516", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-517.jpg", alt: "Création Instagram 517", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-518.jpg", alt: "Création Instagram 518", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-519.jpg", alt: "Création Instagram 519", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-520.jpg", alt: "Création Instagram 520", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-521.jpg", alt: "Création Instagram 521", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-522.jpg", alt: "Création Instagram 522", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-523.jpg", alt: "Création Instagram 523", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-524.jpg", alt: "Création Instagram 524", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-525.jpg", alt: "Création Instagram 525", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-526.jpg", alt: "Création Instagram 526", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-527.jpg", alt: "Création Instagram 527", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-528.jpg", alt: "Création Instagram 528", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-529.jpg", alt: "Création Instagram 529", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-530.jpg", alt: "Création Instagram 530", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-531.jpg", alt: "Création Instagram 531", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-532.jpg", alt: "Création Instagram 532", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-533.jpg", alt: "Création Instagram 533", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-534.jpg", alt: "Création Instagram 534", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-535.jpg", alt: "Création Instagram 535", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-536.jpg", alt: "Création Instagram 536", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-537.jpg", alt: "Création Instagram 537", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-538.jpg", alt: "Création Instagram 538", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-539.jpg", alt: "Création Instagram 539", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-540.jpg", alt: "Création Instagram 540", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-541.jpg", alt: "Création Instagram 541", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-542.jpg", alt: "Création Instagram 542", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-543.jpg", alt: "Création Instagram 543", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-544.jpg", alt: "Création Instagram 544", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-545.jpg", alt: "Création Instagram 545", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-546.jpg", alt: "Création Instagram 546", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-547.jpg", alt: "Création Instagram 547", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-548.jpg", alt: "Création Instagram 548", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-549.jpg", alt: "Création Instagram 549", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-550.jpg", alt: "Création Instagram 550", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-551.jpg", alt: "Création Instagram 551", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-552.jpg", alt: "Création Instagram 552", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-553.jpg", alt: "Création Instagram 553", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-554.jpg", alt: "Création Instagram 554", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-555.jpg", alt: "Création Instagram 555", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-556.jpg", alt: "Création Instagram 556", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-557.jpg", alt: "Création Instagram 557", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-558.jpg", alt: "Création Instagram 558", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-559.jpg", alt: "Création Instagram 559", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-560.jpg", alt: "Création Instagram 560", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-561.jpg", alt: "Création Instagram 561", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-562.jpg", alt: "Création Instagram 562", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-563.jpg", alt: "Création Instagram 563", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-564.jpg", alt: "Création Instagram 564", description: "Création ongulaire Instagram", category: "Nail Art" },
  { src: "/gallery/instagram2/ig-565.jpg", alt: "Création Instagram 565", description: "Création ongulaire Instagram", category: "Nail Art" },
];

export const GALLERY_CATEGORIES = ["Tous", "Gel", "Acryl", "Nail Art"] as const;

export const SHOOTING_PHOTOS = [
  { src: "/gallery/stacy-portrait-01.webp", alt: "Portrait Stacy 1" },
  { src: "/gallery/stacy-portrait-02.webp", alt: "Portrait Stacy 2" },
  { src: "/gallery/stacy-portrait-03.webp", alt: "Portrait Stacy 3" },
  { src: "/gallery/stacy-portrait-04-roses.webp", alt: "Portrait Stacy avec roses" },
  { src: "/gallery/stacy-portrait-05-nailart.webp", alt: "Portrait Stacy nail art" },
];

export const SOCIAL_STATS = [
  { platform: "Instagram", handle: "@stacyfullofacrylics", count: "15.2K", color: "from-purple-500 via-pink-500 to-orange-400" },
  { platform: "TikTok", handle: "@stacyfullnails", count: "48.7K", color: "#1A1A1A" },
  { platform: "Snapchat", handle: "@stacyfull", count: "8.3K", color: "#FFFC00" },
];

export const VISION = {
  title: "Ma Vision",
  text: "Créer et innover constamment dans l'industrie de la beauté et être à l'avant-garde de la mode, en créant toujours des tendances dans le 'Nail Art'.",
  image: SHOOTING_PHOTOS[3].src,
} as const;

export const MISSION = {
  title: "Ma Mission",
  items: [
    "Donner plus de légitimité à la profession de prothésiste ongulaire.",
    "Me prouver que je peux être une femme inspirante.",
    "Satisfaire aux attentes des clients.",
    "Aider les femmes à avoir plus confiance en elles grâce à mon travail.",
  ],
  image: SHOOTING_PHOTOS[3].src,
} as const;

export const CONTACT = {
  phone: "672461121",
  email: "cchouakedianastacy@gmail.com",
  location: "LOGPOM COLLEGE LE NIL\nOU LOGBESSOU STATION NICKEL OIL",
  whatsapp: "https://wa.me/message/Q66A6EE7D7HME1",
  instagram: "https://www.instagram.com/stacyfullofacrylics?igsh=MzE2cGZ2cHYya3Nx&utm_source=qr",
  tiktok: "https://www.tiktok.com/@stacyfullnails",
  snapchat: "https://www.snapchat.com/add/stacyfull",
} as const;
